### ISSUE TITLE
Not sure if this is correct way but ....

### ISSUE THREAD

**Issue by helgjohn** [Marsman1970/SKR-V1.3-Bootloader#1]
Hey will this boot loader work for skr 1.4 turbo ? whit lpc1769 ? i have looked every where this is the closest i have got to some thing that remotely looks like a fix for my board that suddenly decided to not take any comm via Sd card but works just fine as is via octoprint but i need to update somethings like marlin software but no luck... i think maybe boot loader is a bit wanky.... i hav tested most other options i can think of so here it goes..

**Comment by Marsman1970** [comment]
Use the one that says lpc 1769 https://github.com/Marsman1970/SKR-V1.3-Bootloader
I got that of a skr 1.4 turbo

**Comment by helgjohn** [comment]
ok will try thanks

**Comment by helgjohn** [comment]
Do you know of any tutorial on how to connect and flash the skr card ? i m not sure how to do this need some training wheels. any tips will be greatly welcome..

**Comment by helgjohn** [comment]
closing issue there doesent seem to be any solvent out there will park the SKR card in the bin and buy a duet hopefully that will function better SKR card Waist of money and time.
